bayes_people_tracker:
    filter_type: "UKF"                                         # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
    cv_noise_params:                                           # The noise for the constant velocity prediction model
        x: 1.4
        y: 1.4
        std_limit: 1.0                                         # upper limit for the standard deviation of the estimated position 
    detectors:                                                 # Add detectors under this namespace
        upper_body_detector:                                   # Name of detector (used internally to identify them). Has to be unique.
            topic: "/upper_body_detector/bounding_box_centres" # The topic on which the geometry_msgs/PoseArray is published
            observation_model: "CARTESIAN"                     # Obeservation model: CARTESIAN or POLAR
            noise_params:                                      # The noise (standard deviation) for the cartesian or polar observation model
                x: 0.5
                y: 0.5
            matching_algorithm: "NN"                           # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
            seq_size: 5                                        # Minimum number of observations for new track creation
            seq_time: 0.2                                      # Minimum interval between observations for new track creation
        object3d_detector:
            topic: "/object3d_detector/poses"
            observation_model: "CARTESIAN"
            noise_params:
                x: 0.1
                y: 0.1
            matching_algorithm: "NN"
            seq_size: 4
            seq_time: 0.3
        leg_detector:
            topic: "/to_pose_array/leg_detector"
            observation_model: "CARTESIAN"
            noise_params:
                x: 0.2
                y: 0.2
            matching_algorithm: "NN"
            seq_size: 5
            seq_time: 0.2
        rgbd_leg_detector:
            topic: "/rgbd_leg_detector/poses"
            observation_model: "CARTESIAN"
            noise_params:
                x: 0.5
                y: 0.5
            matching_algorithm: "NN"
            seq_size: 5
            seq_time: 0.2
