set(_CATKIN_CURRENT_PACKAGE "podcar")
set(podcar_VERSION "0.0.0")
set(podcar_MAINTAINER "podcar <podcar@todo.todo>")
set(podcar_PACKAGE_FORMAT "2")
set(podcar_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(podcar_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(podcar_BUILDTOOL_DEPENDS "catkin")
set(podcar_BUILDTOOL_EXPORT_DEPENDS )
set(podcar_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(podcar_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(podcar_TEST_DEPENDS )
set(podcar_DOC_DEPENDS )
set(podcar_URL_WEBSITE "")
set(podcar_URL_BUGTRACKER "")
set(podcar_URL_REPOSITORY "")
set(podcar_DEPRECATED "")